### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by unllked** [isFakeAccount/GamerTagIDGrabber#1]
If you could make a new one, if possible psn only cause i don't need for xbox

**Comment by isFakeAccount** [comment]
I recommend creating a new fork and deleting the sections of code you don't want.

**Comment by isFakeAccount** [comment]
This should work
```
import logging
import os

import aiohttp
import discord
import psnawp_api
from dotenv import load_dotenv

bot = discord.Bot()


@bot.event
async def on_ready():
    logger.info(f"We have logged in as Discord User {bot.user}.")


@bot.slash_command(description="To grab the PSNID of PSN user.", guild_ids=[793952307103662102])
async def grab_psnid(ctx, gamer_tag: str):
    logger.info(f"Received PSN gamertag: {gamer_tag.strip()}.")
    if ctx.channel_id == 924193319507079238:
        try:
            user = psnawp.user(online_id=gamer_tag)
            logger.info(f"Response PSN {user}.")
            await ctx.respond(f"{user.online_id}: {user.account_id}")
        except Exception:
            await ctx.respond(f"GamerTag {gamer_tag} not found.")
    else:
        await ctx.respond("The command only works in the #gamer-tag-id-grabber channel.")


def main():
    bot.run(os.getenv("TOKEN"))


if __name__ == '__main__':
    load_dotenv('config.env')
    psnawp = psnawp_api.psnawp.PSNAWP(os.getenv('NPSSO_CODE'))
    logger = logging.getLogger("GammerTagIDGrabber")
    logger.setLevel(logging.DEBUG)

    log_stream = logging.StreamHandler()
    log_stream.setLevel(logging.INFO)
    formatter = logging.Formatter('[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s')
    log_stream.setFormatter(formatter)
    logger.addHandler(log_stream)

    client = psnawp.me()
    logger.info(f"Logged in as PSN ID: {client.get_online_id()}.")
    main()
```

**Comment by unllked** [comment]
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by unllked** [comment]
I've installed the pycord ver on the requirements, now gives me this:     if len(npsso_token) != 64:
TypeError: object of type 'NoneType' has no len()

**Comment by isFakeAccount** [comment]
Follow the instructions [here](https://github.com/isFakeAccount/psnawp/blob/master/README.md) and get NPSSO code

and put NPSSO code in the line

```
psnawp = psnawp_api.psnawp.PSNAWP("<64 character npsso code>")
```

or you can create a file called `config.env` and put NPSSO code there

```
NPSSO_CODE=<64 character npsso code>
```

**Comment by unllked** [comment]
I put the npsso code there:  psnawp = psnawp_api.psnawp.PSNAWP(os.getenv('NPSSO_CODE'))
but it's still giving me that error

**Comment by unllked** [comment]
Now, with this code the log system gets the info to the npsso code and my bot, but the bot doesn't reply to the commands. I want that it gives me the account id from the psn username


import logging
import os

import aiohttp
import discord
import psnawp_api
from dotenv import load_dotenv
from discord.ext import commands
bot = commands.Bot(command_prefix="!")
bot = discord.Bot()
@bot.event
async def on_ready():
    logger.info(f"We have logged in as Discord User {bot.user}.")


@bot.command()
async def id(ctx, gamer_tag: str):
    logger.info(f"Received PSN gamertag: {gamer_tag.strip()}.")
    if ctx.channel_id == mychannelid:
        try:
            user = psnawp.user(online_id=gamer_tag)
            logger.info(f"Response PSN {user}.")
            await ctx.channel.send(f"{user_online_id.account_id}:")
        except Exception:
            await ctx.channel.send(f"GamerTag {gamer_tag} not found.")
    else:
        await ctx.channel.send("The command only works in the #gamer-tag-id-grabber channel.")


def main():
    bot.run("token")


if __name__ == '__main__':
    load_dotenv('config.env')
    psnawp = psnawp_api.psnawp.PSNAWP('npsso code')
    logger = logging.getLogger("GammerTagIDGrabber")
    logger.setLevel(logging.DEBUG)

    log_stream = logging.StreamHandler()
    log_stream.setLevel(logging.INFO)
    formatter = logging.Formatter('[%(asctime)s] %(levelname)s [%(name)s.%(funcName)s:%(lineno)d] %(message)s')
    log_stream.setFormatter(formatter)
    logger.addHandler(log_stream)

    client = psnawp.me()
    logger.info(f"Logged in as PSN ID: {client.get_online_id()}.")
    main()

**Comment by isFakeAccount** [comment]
I recommend asking pycord questions here https://pycord.dev/discord

**Comment by unllked** [comment]
I fixed it myself, now it sends the online id when i send the command and the psn username, Thanks for helping

**Comment by unllked** [comment]
For you would it be possible like to add a command that converts the account id into hex decimal?

Example: !hex account_id

and the bot would send the hexadecimal
