### ISSUE TITLE
when i start main.py

### ISSUE THREAD

**Issue by baffocarboni12** [isFakeAccount/GamerTagIDGrabber#3]
Traceback (most recent call last):
  File "/home/shy/GamerTagIDGrabber/main.py", line 18, in <module>
    bot = hikari.GatewayBot(os.getenv('TOKEN'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shy/.local/lib/python3.11/site-packages/hikari/impl/gateway_bot.py", line 345, in __init__
    self._token = token.strip()
                  ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by isFakeAccount** [comment]
You need to give the environment variable duh.

**Comment by baffocarboni12** [comment]
I don't really understand, what should do for fixing it? and do u have discord? at least I can show you

**Comment by isFakeAccount** [comment]
> I don't really understand, what should do for fixing it? and do u have discord? at least I can show you

https://dev.to/jakewitcher/using-env-files-for-environment-variables-in-python-applications-55a1
